version: '3.8'
services:
  # customer-service
  api-service:
    image: loanburger/customer-service:latest
    ports:
      - '5000:5000'
    environment:
      ASPNETCORE_URLS: http://+:5000

  # the customer-spa
  customer-spa:
    image: loanburger/customer-spa:latest
    ports:
      - '3000:3000'
    environment:
      ASPNETCORE_URLS: http://+:3000
