name: Create Release

on:
  push:
    tags:
      - 'release-v*.*.*'
jobs:
  create_release:
    name: Create Release

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.yarnpkg.com/'

    - name: Install dependencies
      run: |
        cd project
        yarn install
    - name: Get commit message
      id: get_commit_message
      run: |
        COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
        echo "::set-output name=commit_message::${COMMIT_MESSAGE}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.IO_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Commit message:
          ${{ steps.get_commit_message.outputs.commit_message }}
        draft: false
        prerelease: false
